name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: AndresMorelos.Invoncify
          installers-regex: 'Setup.*(exe|msi|msix|appx)(bundle){0,1}$'
          token: ${{ secrets.GH_TOKEN }}
